
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-19T21:28:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aceea3a4985f667979e4d8a5a5b8eeddaf23b7be",
 "version": "2023.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
